;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-word-correctly-and-capitalize
        beginning-of-visual-line
        capitalize-or-endless/capitalize
        colon-or-smart-colon
        downcase-or-endless-downcase
        insert-colon
        insert-space
        jay/left-char
        jay/right-char
        kill-region
        kill-word-correctly-and-capitalize
        meta-return
        mwim-beginning
        mwim-end
        my/delete-backward-and-capitalize
        my/kill-line-dwim
        newline-and-indent
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-meta-return
        org-metaright
        org-return
        org-self-insert-command
        org-shiftdown
        org-shiftleft
        org-shiftright
        org-shiftup
        org-toggle-heading-same-level
        pasteboard-cut-and-capitalize
        pasteboard-paste-spaces-maybe
        pasteboard-paste-without-smart-quotes
        return
        right-word
        smart-forward-sentence
        smart-return
        smart-space
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-recentf
        jay/save-some-buffers
        ))
