
* DONE task 1A
Hi Serj,

Can you take a look at the function replace-smart-quotes

This is mostly working as I want it to, except for two things:

First, this line:

: (" - " . "---")


This works correctly most of the time. For instance, if I have a sentence like this:

: This is the most important thing - to be a good person.

It correctly changes it to this:

: This is the most important thing---to be a good person.

However, I want to make it do this ONLY when it is NOT at the beginning of a line.

Currently, if I have a line like this:

:   - this is a bullet item

It incorrectly gets replaced with this:
:  ---this is a bullet item

That's not what I want.

Can you adjust the function so that it replaces " - " with "---" ONLY when there is other text at the beginning of the line?



* TODO task 1B
Also, can you add a line of code that deletes the string "- " but ONLY IF it comes in the middle of a word, like this:
: spac- es

So that

: spac- es

would become:

: spaces

but again, in a way so that bullet items like this:
: - this is a bullet item

...are unaffected?

I am guessing it will involve some kind of regex search for a string that looks like:

"[:alphanumeric:]- "

Thanks!!


* TODO task 2
I use flyspell-auto-correct-word to quickly correct typos. I use like the flyspell-auto-correct-word command (which I have bound to the ~`~ key) because I invoke it once to get a spelling suggestion, then invoke it again to get the next suggestion, and so on. In this way, I can scroll through various spelling suggestions by hitting the  ~`~ key several times. This works well.

However, I would like to make it so that the correction that I choose automatically gets added to my abbrev-list in abbrev-mode. This used to work automatically, but no longer does.

I found a blog post about how to do this:
http://endlessparentheses.com/ispell-and-abbrev-the-perfect-auto-correct.html

(You can also see my comment there in the comments section.)

This code successfully adds a spelling correction to the abbrev-list automatically. However, I don't like it because instead of using flyspell-auto-correct-word, it uses ispell-word. This means that instead of simply hitting the ~`~ key a few times, I need to go into a menu and choose which spelling correction I want by using the number keys.

Do you know how to make this work with flyspell-auto-correct-word instead of ispell-word? I would like to use flyspell-auto-correct-word as I always have, but so that it automatically adds the correction I choose to my abbrev-list?

Thanks!
