* Note to Rúdi <2015-07-16 Thu 13:00>
Hi Rúdi,

Good idea to have the test files for the smart punctuation, and to keep them around. 

I added a case at the beginning of smart-comma-test.elt---the one I describe here: 

#+BEGIN_EXAMPLE
: You might have a conscious intention to eat healthier, but you forget.

Say the point is on the comma and I hit comma. Current behavior is to do nothing and keep the point on the comma. But this is counterintuitive, because if there is NO comma and I hit comma, it gives me a comma, my point is placed on the space AFTER the comma... Whenever I hit one of those punctuation marks, the point should be placed AFTER the punctuation mark, not stay on it. 
#+END_EXAMPLE

Here are the lines I added to smart-comma-test.elt: 

#+BEGIN_EXAMPLE
Input: You might have a conscious intention to eat healthier^, but you forget. 
Output: You might have a conscious intention to eat healthier,^ but you forget. 
#+END_EXAMPLE

For the same reason, I changed some existing lines in smart-period-test.elt. Here's how the lines looked before:

#+BEGIN_EXAMPLE 
Input: You might have a conscious intention to eat healthier, but you forget ^.
Output: You might have a conscious intention to eat healthier, but you forget..^

Input: You might have a conscious intention to eat healthier, but you forget^.
Output: You might have a conscious intention to eat healthier, but you forget..^ 
#+END_EXAMPLE

Here's the behavior I want:

#+BEGIN_EXAMPLE 
Input: You might have a conscious intention to eat healthier, but you forget ^.
Output: You might have a conscious intention to eat healthier, but you forget..^

Input: You might have a conscious intention to eat healthier, but you forget^.
Output: You might have a conscious intention to eat healthier, but you forget.^ 
#+END_EXAMPLE

These cases are fine as they are:

#+BEGIN_EXAMPLE
Input: You might have a conscious intention to eat healthier, but you forget.^
Output: You might have a conscious intention to eat healthier, but you forget..^

Input: You might have a conscious intention to eat healthier, but you forget..^
Output: You might have a conscious intention to eat healthier, but you forget...^ 
#+END_EXAMPLE

However, if it is too complicated to distinguish between my intention to write a period "." and my intention to write an ellipsis "..." then I am fine with creating an alternative way to enter an ellipsis (e.g. a function insert-ellipsis) so that smart-period didn't have to distinguish between the above cases. In other words, this case... 

#+BEGIN_EXAMPLE
Input: You might have a conscious intention to eat healthier, but you forget.^
Output: You might have a conscious intention to eat healthier, but you forget..^ 
#+END_EXAMPLE

...isn't that important if preserving this functionality makes this case...

#+BEGIN_EXAMPLE
Input: You might have a conscious intention to eat healthier, but you forget^.
Output: You might have a conscious intention to eat healthier, but you forget.^ 
#+END_EXAMPLE

...too complicated.

Another note in that spirit: if eliminating smart-colon makes things easier, that's fine. I can enter colons without the benefit of smart-punctuation spacing. 

However, note this request:

*** TODO [#B] a smart-space exception for org-mode tags

Example:
#+BEGIN_EXAMPLE
* Is this a viable^                                                   :slide: 
#+END_EXAMPLE

Let's say the point is on the carat and I type "business?"

Current output: 
#+BEGIN_EXAMPLE
* Is this a viable business ?slide: 
#+END_EXAMPLE

Desired output:
#+BEGIN_EXAMPLE
* Is this a viable business?^                                          :slide: 
#+END_EXAMPLE

Note that in this request, the colon is preexisting, and I'm typing a smart-period on a line BEFORE the colon appears. Ideally I could enter a period in an org-mode heading without removing the space between the heading and the org-mode tag.

Thank you so much for being so clever ab solving out this increasingly complex problem! :-)

* Update, <2015-07-16 Thu 15:10>
Hi Rúdi,

I made more edits to those files. Specifically:

** I changed this behavior: 

Input: You might have a conscious intention to eat healthier ^, but you forget.
Output: You might have a conscious intention to eat healthier,^ but you forget.
Desired output: You might have a conscious intention to eat healthier, ^but you forget. 

** I also edited the following input line to correct the desired output:

Input: You might have a conscious intention to eat healthier, but you forget ^.

Thanks!

* NOTE-TO-JAY I think it works now

  A couple of notes bear relevance:

  - I changed the following test case in [[file:smart-period-test.elt][smart-period-test.elt]]:

#+BEGIN_EXAMPLE
Input: You might have a conscious intention to eat healthier, but you forget ^.
Output: you might have a conscious intention to eat healthier, but you forget.^
#+END_EXAMPLE

    After your changes, it contained a whitespace in the output after the carat. It didn't seem to me logical, so I removed it. Do you confirm?

* NOTE-TO-RÚDI Answer
Thanks. Actually, I did intend that whitespace. For me, if there's already a space after the last word of the sentence, I'd prefer to make smart-punctuation insert the punctuation but retain the space. I'm adding the space back in in the example.

* NOTE-TO-JAY I think it works now 
- invoking smart punctuation on org headings should be OK now, unless you have a situation such as this one:

#+BEGIN_EXAMPLE
**                                                                     :oops:
#+END_EXAMPLE

    i.e., an empty heading with tags. Are you comfortable with that?

* NOTE-TO-RÚDI Answer
Yes! I'd never enter a period as the first character of a heading, so that's fine. 


