(defvar search-link-cmd "~/gnulisp/searchlink/searchlink.rb")

(defun searchlink (start end)
(interactive "r")
(let* ((txt (delete-and-extract-region start end))
(shell-cmd (format "echo %s | %s" txt search-link-cmd))
(res (shell-command-to-string shell-cmd))
(clean-res (replace-regexp-in-string "\\[.*\\] isn't a Gem::Specification (NilClass instead)\\.\n" "" res)))
;; (message "Sh: %s , res: %s" shell-cmd clean-res)
(insert clean-res)))
